#!/bin/bash
# build-standalone.sh — generate a single-file installer by inlining
# custom.rules, suricata_setup.sh, and zeek_setup.sh into one shell script.
#
# Output: standalone.sh — run with `sudo bash standalone.sh [--force|--iface X]`
set -e
cd "$(dirname "$(readlink -f "$0")")"

OUT=standalone.sh

{
cat <<'HEADER'
#!/bin/bash
# standalone.sh — single-file Suricata 8 + Zeek 8 installer for Ubuntu 22.04.
# Generated by build-standalone.sh; do not edit by hand — edit the source
# scripts and regenerate.
#
# Usage:
#   sudo bash standalone.sh [--force] [--preserve-config] [--iface <name>]
set -e

FORCE=0
PRESERVE=0
IFACE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --preserve-config) PRESERVE=1; shift ;;
    --iface) IFACE="$2"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root" >&2; exit 1
fi

TS="$(date +%Y%m%d-%H%M%S)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "=== standalone install starting ($(date -u +%FT%TZ)) ==="

# ---------- Prior-install detection + backup ----------
SURICATA_PRESENT=0; ZEEK_PRESENT=0
command -v suricata >/dev/null 2>&1 && SURICATA_PRESENT=1
{ [ -x /opt/zeek/bin/zeek ] || command -v zeek >/dev/null 2>&1; } && ZEEK_PRESENT=1

if { [ "$SURICATA_PRESENT" = 1 ] || [ "$ZEEK_PRESENT" = 1 ]; } && [ "$FORCE" = 0 ]; then
  echo "Prior install detected. Re-run with --force (existing configs will be backed up)."
  exit 3
fi
if [ "$SURICATA_PRESENT" = 1 ] && [ -d /etc/suricata ]; then
  cp -a /etc/suricata "/etc/suricata.bak.${TS}"
  echo "Backed up /etc/suricata -> /etc/suricata.bak.${TS}"
  systemctl stop suricata || true
fi
if [ "$ZEEK_PRESENT" = 1 ] && [ -d /opt/zeek/etc ]; then
  cp -a /opt/zeek/etc "/opt/zeek-etc.bak.${TS}"
  echo "Backed up /opt/zeek/etc -> /opt/zeek-etc.bak.${TS}"
  /opt/zeek/bin/zeekctl stop 2>/dev/null || true
fi

# ---------- Interface override ----------
if [ -n "$IFACE" ] && ! ip link show "$IFACE" >/dev/null 2>&1; then
  echo "ERROR: interface '$IFACE' not found" >&2; exit 4
fi

# Helper the inlined scripts call instead of ip-link detection
detect_iface() {
  if [ -n "${IFACE:-}" ]; then
    printf '%s\n' "$IFACE"
  else
    ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -1
  fi
}
export -f detect_iface
export IFACE

# BUNDLE_DIR points at the extracted working dir so the inlined suricata
# setup block can find custom.rules written by the heredoc below.
BUNDLE_DIR="$WORK"
export BUNDLE_DIR

# ---------- Write custom.rules to work dir ----------
cat > "$WORK/custom.rules" <<'CUSTOM_RULES_EOF'
HEADER

# Embed custom.rules verbatim
cat custom.rules

cat <<'MIDDLE'
CUSTOM_RULES_EOF

# Preserve-config short path
if [ "$PRESERVE" = 1 ]; then
  install -d -m 0755 /var/lib/suricata/rules
  cp "$WORK/custom.rules" /var/lib/suricata/rules/custom.rules
  cat /var/lib/suricata/rules/custom.rules >> /var/lib/suricata/rules/suricata.rules
  suricata-update || true
  [ -x /opt/zeek/intel/build-intel.sh ] && /opt/zeek/intel/build-intel.sh || true
  systemctl restart suricata || true
  /opt/zeek/bin/zeekctl deploy 2>/dev/null || true
  echo "=== preserve-config install complete ==="
  exit 0
fi


# =========================================================================
# ============= INLINED: suricata_setup.sh ================================
# =========================================================================
(
MIDDLE

# Inline suricata_setup.sh with two patches:
#  1. If PRIMARY_IF_OVERRIDE is set, use it instead of ip -o link detection
#  2. Drop the shebang + exec>redirect + first "set +e" (outer script owns those)
sed -e '1,4d' -e 's|^PRIMARY_IF=.*ip -o link show.*|PRIMARY_IF=$(detect_iface)|' suricata_setup.sh

cat <<'BETWEEN'
)

# =========================================================================
# ============= INLINED: zeek_setup.sh ====================================
# =========================================================================
(
BETWEEN

sed -e '1,9d' -e 's|^PRIMARY_IF=.*ip -o link show.*|PRIMARY_IF=$(detect_iface)|' zeek_setup.sh

cat <<'FOOTER'
)

echo ""
echo "=== standalone install complete ==="
echo "Log: /var/log/suricata-setup.log"
FOOTER
} > "$OUT"

chmod +x "$OUT"
echo "Built: $(pwd)/$OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"

# Syntax check
bash -n "$OUT" && echo "bash -n: OK"
